name: cpanal
description: "Attendance System for Companies."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  webview_flutter:
  flutter_widget_from_html:
  flutter_contacts:
  excel: ^4.0.3
  media_store_plus:
  open_filex: ^4.0.2
  phone_numbers_parser:
  webview_flutter_android:
  webview_flutter_wkwebview:
  auto_animated: ^3.2.0
  pretty_dio_logger:
  syncfusion_flutter_xlsio:
  spreadsheet_decoder:
  flutter_slidable:
  syncfusion_flutter_pdfviewer:
  flutter_pdfview: ^1.4.0+1
  internet_connection_checker:
  just_audio:
  record:
  flutter_staggered_grid_view:
  photo_view:
  fluttertoast:
  flutter_bloc:
  app_settings:
  clipboard:
  flutter_local_notifications:
  flutter_html:
  shimmer:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  connectivity_plus: ^6.1.2
  cupertino_icons: 1.0.6
  device_info_plus: ^11.2.2
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  file_picker: ^8.3.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  flutter_custom_tabs: ^2.1.0
  flutter_native_splash: ^2.4.4
  flutter_svg: 2.0.10+1
  font_awesome_flutter: ^10.8.0
  go_router: ^14.7.2
  graphview: ^1.2.0
  hive_flutter: ^1.1.0
  http: ^1.3.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  intl: any
  intl_phone_field: ^3.2.0
  local_auth: ^2.3.0
  location: ^8.0.0
  mime: ^2.0.0
  wifi_iot:
  mobile_scanner: ^6.0.6
  network_info_plus: ^6.1.3
  nfc_manager: ^3.5.0
  package_info_plus: ^8.1.4
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.1
  syncfusion_flutter_calendar: ^28.2.3
  syncfusion_flutter_pdf: ^28.2.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  wifi_scan: ^0.4.1+1
  yaml: ^3.1.3
  geocoding:
  geolocator: ^10.1.0
dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_images/splash_screen_background.png
  android: true
  ios: true
  web: false
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/lang/
    - pubspec.yaml
    - assets/images/alerts_images/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/splash_images/
    - assets/images/general_images/
    - assets/images/onboarding_images/
    - assets/images/login_images/
    - assets/images/home_images/
    - assets/images/home_images/bottom_bar_images/
    - assets/images/home_images/floating_actions_buttons_images/
    - assets/images/home_images/appbar_images/
    - assets/images/notifications_images/
    - assets/images/profiles_images/
    - assets/images/company_info_images/
    - assets/images/fingerprints_images/

  fonts:
    - family: NalikaSignature
      fonts:
        - asset: assets/fonts/NalikaSignature/NalikaSignature.otf
        - asset: assets/fonts/NalikaSignature/NalikaSignature.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Arabic.ttf
