// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Zu2SYLI-V3wmbwss7LQkuBfZL4FBlFw',
    appId: '1:1014851799383:web:85151567e27f5654c89612',
    messagingSenderId: '1014851799383',
    projectId: 'rm-sys',
    authDomain: 'rm-sys.firebaseapp.com',
    storageBucket: 'rm-sys.firebasestorage.app',
    measurementId: 'G-LV7NL9HJ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWMfBrDtEUx1uIHSZrl6YB2rwClwuN2k',
    appId: '1:1014851799383:android:999aba654f6f0b40c89612',
    messagingSenderId: '1014851799383',
    projectId: 'rm-sys',
    storageBucket: 'rm-sys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsD7cVmGH-QGbhOTz0J8cwom-TYbUBAs',
    appId: '1:1014851799383:ios:ef98684154c2c4e8c89612',
    messagingSenderId: '1014851799383',
    projectId: 'rm-sys',
    storageBucket: 'rm-sys.firebasestorage.app',
    iosBundleId: 'com.rightminddev.cpanal',
  );
}
